global:
  scrape_interval: 20s
  scrape_timeout: 10s
  evaluation_interval: 20s

scrape_configs:
  - job_name: polymarket-bot
    metrics_path: /prometheus/metrics
    static_configs:
      - targets:
          - polymarket-bot:8097
  - job_name: ingester-master
    metrics_path: /prometheus/metrics
    static_configs:
      - targets:
          - ingester-master:8098
  - job_name: ingester-worker
    metrics_path: /prometheus/metrics
    dns_sd_configs:
      - names:
          - ingester-worker
        type: A
        port: 8099
  - job_name: alloy
    static_configs:
      - targets:
          - alloy:12345
  - job_name: loki
    static_configs:
      - targets:
          - loki:3100
