use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

pub use crate::domain::{
    BinanceAggregateTradeRecord, BinanceBtcusdtOpenInterestRecord, BinanceOneSecondKlineRecord,
};

#[derive(Debug, Clone, PartialEq)]
pub struct BinanceL2OneSecondFeature {
    pub symbol: String,
    pub second_start: DateTime<Utc>,
    pub source_event_timestamp: DateTime<Utc>,
    pub provider_received_at: DateTime<Utc>,
    pub available_at: DateTime<Utc>,
    pub source_update_id: i64,
    pub feature_schema_version: String,
    pub quality_status: String,
    pub midpoint: Decimal,
    pub microprice: Decimal,
    pub spread_bps: Decimal,
    pub bid_depth_5: Decimal,
    pub ask_depth_5: Decimal,
    pub imbalance_5: Decimal,
    pub bid_depth_10: Decimal,
    pub ask_depth_10: Decimal,
    pub imbalance_10: Decimal,
    pub bid_depth_20: Decimal,
    pub ask_depth_20: Decimal,
    pub imbalance_20: Decimal,
    pub bid_depth_slope_20: Decimal,
    pub ask_depth_slope_20: Decimal,
    pub bid_depth_concentration_20: Decimal,
    pub ask_depth_concentration_20: Decimal,
    pub bid_quote_replenishment_1s: Decimal,
    pub ask_quote_replenishment_1s: Decimal,
    pub bid_quote_churn_1s: Decimal,
    pub ask_quote_churn_1s: Decimal,
    pub midpoint_change_bps_1s: Decimal,
    pub spread_bps_delta_1s: Decimal,
    pub depth_20_change_bps_1s: Decimal,
    pub imbalance_20_delta_1s: Decimal,
    pub midpoint_change_bps_5s: Decimal,
    pub spread_bps_delta_5s: Decimal,
    pub depth_20_change_bps_5s: Decimal,
    pub imbalance_20_delta_5s: Decimal,
    pub midpoint_change_bps_15s: Decimal,
    pub spread_bps_delta_15s: Decimal,
    pub depth_20_change_bps_15s: Decimal,
    pub imbalance_20_delta_15s: Decimal,
    pub midpoint_change_bps_30s: Decimal,
    pub spread_bps_delta_30s: Decimal,
    pub depth_20_change_bps_30s: Decimal,
    pub imbalance_20_delta_30s: Decimal,
    pub midpoint_change_bps_60s: Decimal,
    pub spread_bps_delta_60s: Decimal,
    pub depth_20_change_bps_60s: Decimal,
    pub imbalance_20_delta_60s: Decimal,
}
