SELECT
  feature.symbol,
  feature.second_start,
  feature.source_event_timestamp,
  feature.provider_received_at,
  feature.available_at,
  feature.source_update_id,
  feature.midpoint::double precision AS midpoint,
  feature.microprice::double precision AS microprice,
  feature.spread_bps::double precision AS spread_bps,
  feature.bid_depth_5::double precision AS bid_depth_5,
  feature.ask_depth_5::double precision AS ask_depth_5,
  feature.imbalance_5::double precision AS imbalance_5,
  feature.bid_depth_10::double precision AS bid_depth_10,
  feature.ask_depth_10::double precision AS ask_depth_10,
  feature.imbalance_10::double precision AS imbalance_10,
  feature.bid_depth_20::double precision AS bid_depth_20,
  feature.ask_depth_20::double precision AS ask_depth_20,
  feature.imbalance_20::double precision AS imbalance_20,
  feature.bid_depth_slope_20::double precision AS bid_depth_slope_20,
  feature.ask_depth_slope_20::double precision AS ask_depth_slope_20,
  feature.bid_depth_concentration_20::double precision AS bid_depth_concentration_20,
  feature.ask_depth_concentration_20::double precision AS ask_depth_concentration_20,
  feature.bid_quote_replenishment_1s::double precision AS bid_quote_replenishment_1s,
  feature.ask_quote_replenishment_1s::double precision AS ask_quote_replenishment_1s,
  feature.bid_quote_churn_1s::double precision AS bid_quote_churn_1s,
  feature.ask_quote_churn_1s::double precision AS ask_quote_churn_1s,
  feature.midpoint_change_bps_1s::double precision AS midpoint_change_bps_1s,
  feature.spread_bps_delta_1s::double precision AS spread_bps_delta_1s,
  feature.depth_20_change_bps_1s::double precision AS depth_20_change_bps_1s,
  feature.imbalance_20_delta_1s::double precision AS imbalance_20_delta_1s,
  feature.midpoint_change_bps_5s::double precision AS midpoint_change_bps_5s,
  feature.spread_bps_delta_5s::double precision AS spread_bps_delta_5s,
  feature.depth_20_change_bps_5s::double precision AS depth_20_change_bps_5s,
  feature.imbalance_20_delta_5s::double precision AS imbalance_20_delta_5s,
  feature.midpoint_change_bps_15s::double precision AS midpoint_change_bps_15s,
  feature.spread_bps_delta_15s::double precision AS spread_bps_delta_15s,
  feature.depth_20_change_bps_15s::double precision AS depth_20_change_bps_15s,
  feature.imbalance_20_delta_15s::double precision AS imbalance_20_delta_15s,
  feature.midpoint_change_bps_30s::double precision AS midpoint_change_bps_30s,
  feature.spread_bps_delta_30s::double precision AS spread_bps_delta_30s,
  feature.depth_20_change_bps_30s::double precision AS depth_20_change_bps_30s,
  feature.imbalance_20_delta_30s::double precision AS imbalance_20_delta_30s,
  feature.midpoint_change_bps_60s::double precision AS midpoint_change_bps_60s,
  feature.spread_bps_delta_60s::double precision AS spread_bps_delta_60s,
  feature.depth_20_change_bps_60s::double precision AS depth_20_change_bps_60s,
  feature.imbalance_20_delta_60s::double precision AS imbalance_20_delta_60s
FROM polymarket.binance_spot_btcusdt_l2_training_features feature
WHERE feature.symbol = 'BTCUSDT'
  AND feature.available_at >= %(batch_start)s - interval '2 seconds'
  AND feature.available_at < %(batch_end)s
ORDER BY feature.available_at, feature.second_start;
